package controllers;

public enum Action {
	CHANGE_IMAGE, ACCEPT, CHANGE_IMAGE_PLAY, START, END, SELECT_TYPE, SELECT_IMAGE, PAUSE_OR_PLAY_VIDEO, EDIT, AUTO_PAUSE_VIDEO, SAVE, SAVE_AS, DENCITY_PART, START_NEW_PERIOD
}